dataset: [Helpdesk, BPI2012_Full, BPI2012_W, BPI2012_C, BPI2012_WC, BPI2013_Closed, BPI2013_Incidents, EnvPermit, Sepsis, Nasa, BPI2017_Full, BPI2019]
model_config: exhaustive_config
cv_folds: 5
ncores: 1
train_pct: 0.8 # if cv_folds: 1 train_pct specifies the percentage of cases used for training. remaining cases are the test cases
seed: 42
choice_tracker_keys_nap: [] # ['prob_local', 'prob_global', 'len', 'dist_local', 'dist_global', 'n_remaining_candidates'] # will only track when ncores=1
choice_tracker_keys_rtp: [] # ['prob_local', 'prob_global', 'len', 'dist_local', 'dist_global', 'n_remaining_candidates'] # will only track when ncores=1
parallelization_lib: multiprocessing  # joblib or multiprocessing - might have effects regarding worker spin-up times depending on 
                                      # the OS (multiprocessing might lead to increased worker spin-up times during prediction on 
                                      # Windows machines) - larger datasets still experience increased worker spin-up times on 
                                      # Windows machines - we advise to use UNIX based systems for faster parallel processing